version: '3'

services:
  server:
    build: server/
    depends_on:
      - 'database'
    ports:
      - '8000:8000'
    env_file:
      - server/.env

  client:
    build: client/
    depends_on:
      - 'server'
    ports:
      - '3000:3000'

  database:
    build:
      context: .
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=kstan
      - POSTGRES_USER=joshua
      - POSTGRES_PASSWORD=1001
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data

#   database:
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=kstan
#       - POSTGRES_USER=joshua
#       - POSTGRES_PASSWORD=1001
#       - PGDATA=/Library/PostgreSQL/13/data
#       # - PGDATA=/usr/local/var/postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       # - data:/Library/PostgreSQL/13/data/database
#       - data:/var/lib/postgresql/data
#       # - ~/data:/usr/local/var/postgres
#       # - data:/dbdata
# volumes:
#   data:

